name: Publish to Nuget

on:
  release:
    types: [published]

env:
  PROJECT_NAME: Date.Fns.Net

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore src/Date.Fns.Net/Date.Fns.Net/$PROJECT_NAME.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore src/Date.Fns.Net/Date.Fns.Net/$PROJECT_NAME.csproj
    - name: Pack
      run: dotnet pack  --no-build -c Release src/Date.Fns.Net/Date.Fns.Net/$PROJECT_NAME.csproj -o .
    - name: Push
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -n 1
